name: auto-clang-format
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: '.'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 20
        inplace: True
        
    - uses: EndBug/add-and-commit@v10
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: ':art: Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
